require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/wine_types", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # WineType. As you add validations to WineType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WineType.create! valid_attributes
      get wine_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      wine_type = WineType.create! valid_attributes
      get wine_type_url(wine_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_wine_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      wine_type = WineType.create! valid_attributes
      get edit_wine_type_url(wine_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WineType" do
        expect {
          post wine_types_url, params: { wine_type: valid_attributes }
        }.to change(WineType, :count).by(1)
      end

      it "redirects to the created wine_type" do
        post wine_types_url, params: { wine_type: valid_attributes }
        expect(response).to redirect_to(wine_type_url(WineType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WineType" do
        expect {
          post wine_types_url, params: { wine_type: invalid_attributes }
        }.to change(WineType, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post wine_types_url, params: { wine_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wine_type" do
        wine_type = WineType.create! valid_attributes
        patch wine_type_url(wine_type), params: { wine_type: new_attributes }
        wine_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the wine_type" do
        wine_type = WineType.create! valid_attributes
        patch wine_type_url(wine_type), params: { wine_type: new_attributes }
        wine_type.reload
        expect(response).to redirect_to(wine_type_url(wine_type))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        wine_type = WineType.create! valid_attributes
        patch wine_type_url(wine_type), params: { wine_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested wine_type" do
      wine_type = WineType.create! valid_attributes
      expect {
        delete wine_type_url(wine_type)
      }.to change(WineType, :count).by(-1)
    end

    it "redirects to the wine_types list" do
      wine_type = WineType.create! valid_attributes
      delete wine_type_url(wine_type)
      expect(response).to redirect_to(wine_types_url)
    end
  end
end
